baseURL = 'https://fog-observation-portal.pages.dev/'
title = '∴ Fog Observation Portal ∵' # 英語タイトルをメインに
defaultContentLanguage = 'en'        # ★ここを英語(en)に変更！

[languages]
  # --- 1. 英語（メイン） ---
  [languages.en]
    languageName = 'English'
    contentDir = 'content/en'
    weight = 1  # 優先順位を1位に
    title = "∴ Fog <br class='mobile-break'>Observation <br class='mobile-break'>Portal ∵"
    
    # 英語メニュー（ここをアクティブにする）
    # [[languages.en.menu.main]]
    #     identifier = 'new'
    #     pre = '★'
    #     name = 'New!'
    #     url = '/'
    #     weight = 1

    # [[languages.en.menu.main]]
    #     identifier = 'random'
    #     pre = 'x'
    #     name = 'Random Grain'
    #     url = '#'
    #     weight = 2

    [[languages.en.menu.main]]
        identifier = 'blog'
        pre = 'μ'
        name = 'Book Shelf 〈Blog〉'
        url = '/posts/'  # 英語がメインになったので /en/posts ではなく /posts/ でOKになります
        weight = 3

    # [[languages.en.menu.main]]
    #     identifier = 'sns'
    #     pre = '⨳'
    #     name = 'Interference Shelf 〈Social〉'
    #     url = 'https://twitter.com/your_id'
    #     weight = 4

    # [[languages.en.menu.main]]
    #     identifier = 'media'
    #     pre = 'Σ'
    #     name = 'Membrane Shelf 〈Gallery〉'
    #     url = '/media/'
    #     weight = 5

    # [[languages.en.menu.main]]
    #     identifier = 'books'
    #     pre = 'Ψ'
    #     name = 'Structure Shelf 〈Books〉'
    #     url = '/books/'
    #     weight = 6

    # [[languages.en.menu.main]]
    #     identifier = 'shop'
    #     pre = '∞'
    #     name = 'Desire Shelf 〈Shop〉'
    #     url = 'https://yourshop.base.shop'
    #     weight = 7

  # --- 2. 日本語（サブ） ---
  [languages.ja]
    languageName = '日本語'
    contentDir = 'content/ja'
    weight = 2
    title = '∴霧観測窓∵'
    
     [[languages.ja.menu.main]]
         identifier = 'blog'
         pre = 'μ'
         name = '本棚〈ブログ〉'
         url = '/posts/' 
         weight = 3

# disableKinds = ["taxonomy", "term"]